# Generated by Django 5.1.2 on 2024-10-28 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='ItemsBuy',
            new_name='ItemBuy',
        ),
    ]
