# Generated by Django 5.1.2 on 2024-10-28 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_rename_items_item_rename_itemsbuy_itembuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ShoppingList',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.shoppinglist'),
        ),
    ]
